run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/utsmannn/vpsctl

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck

    # Exclude known linters from partially generated files
    - path: api/routes\.go
      linters:
        - unused
